name: tahlil_front
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dropdown_button2: ^2.3.9
  file: ^7.0.0
  file_picker: ^8.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  go_router: ^14.1.3
  intl: ^0.19.0
  shamsi_date: ^1.0.2
  syncfusion_flutter_calendar: ^25.2.6+1
  syncfusion_flutter_datagrid: ^25.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/