name: Front-end Deploy

on:
  push:
    branches:
      - main
    # paths:
    #   - tahlil_front/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tahlil_front

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
      - name: Check Flutter Version
        run: flutter --version
      - name: Build
        run: flutter build web --release --base-href '/' --dart-define=base_url=pezeshkan-sharif.liara.run --dart-define=base_scheme=https
      - name: Push Build Files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
