name: Front-end Deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Deploy
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: liara deploy --api-token="$LIARA_TOKEN" --app="pezeshkan-sharif-front" --port=3000 --platform=static --detach
