name: Front-end Deploy

on:
  push:
    branches:
      - main
    paths:
      - tahlil_front/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tahlil_front

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
      - name: Install Liara
        run: |
          npm i -g @liara/cli@4
      - name: Check Flutter Version
        run: flutter --version
      - name: Build
        run: flutter build web --release --base-href '/' --dart-define=base_url=pezeshkan-sharif.liara.run --dart-define=base_scheme=https
      - name: Deploy
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: liara deploy --api-token="$LIARA_TOKEN" --app="pezeshkan-sharif-front" --port=3000 --platform=static --detach
