name: Front-end Deploy

on:
  push:
    branches:
      - main
    paths:
      - tahlil_front/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tahlil_front

    steps:
      - uses: actions/checkout@v4 # Only works with v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter pub get
      - run: flutter --version
      - run: flutter build web --release --base-href '/'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
